Correcting OSG SOFTWARE-636: java version check fails with wrong version even if there is a problem running java (such as the wrong path, or not enough heap size)
git-svn-id: https://codeforge.lbl.gov/anonscm/bestman@82 f407c832-ab63-4b9d-b5b1-2a9f91e557d8

diff --git a/sources/setup/bestman.in/bestman.server.in b/sources/setup/bestman.in/bestman.server.in
--- a/sources/setup/bestman.in/bestman.server.in
+++ b/sources/setup/bestman.in/bestman.server.in
@@ -170,6 +170,12 @@ Ver_separator() {
 }
 JAVAEXE=$JAVA_HOME/bin/java
 JVR=`$JAVAEXE -version 2>&1`
+RTN=$?
+if [ $RTN -ne 0 ]; then
+    echo "Executing Java version check failed with error:"
+    echo $JVR
+    exit 1
+fi
 JVR=`echo $JVR | sed 's/[^0-9. ]//g'`
 JVR=`echo $JVR | sed 's/\./ /g'`
 Ver_separator $JVR
